[workspace]
resolver = "2"
members = [
    "passport_auth",
    "passport_core"
]

[workspace.dependencies]
async-trait = "0.1"
thiserror = { version = "2.0" }
bcrypt = { version = "0.16" }
tracing = { version = "0.1" }
passport_core = { path = "./passport_core" }
