[package]
name = "passport_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
passport_core = { workspace = true }
